replicaCount: 2

image:
  repository: nanajanashia/argocd-app
  pullPolicy: Always
  tag: "1.2"

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  create: true  # Set this to true to create a service account, or false if not needed
  name: ""      # Leave empty to let Kubernetes generate a name, or provide a specific name if needed

ingress:
  enabled: true
  # Define the host name you want to use to access your app
  hosts:
    - host: myapp.local  # Change this to your desired domain or subdomain
      paths:
        - /
  # Optional: Annotations to configure things like path rewrites
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  # Optional: TLS configuration for HTTPS (if you want to secure your app)
  tls: []
